name: Docker Buildx Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show system info
        run: |
          uname -a
          lsb_release -a || cat /etc/os-release
          hostnamect
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image with buildx (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: test-image:latest

      - name: Run built image
        run: docker run --rm test-image:latest
      - name: Check Buildx Builder
        run: docker buildx ls

      - name: Debug buildx
        run: |
          export DEBUG=1
          docker buildx build --load --tag test-image-debug:latest .


