name: Docker Buildx Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show Buildx version
        run: docker buildx version

      - name: Show Buildx builders
        run: docker buildx ls

      - name: Build Docker image with buildx (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: test-image:latest

      - name: Run built image
        run: docker run --rm test-image:latest

