name: test

on:
  push:
    branches: [ main ]

jobs:
  example-job:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Check Node.js version
        run: read name

